import { useEffect, useState } from "react";
import { api, messageOf } from "../../api/client.js";
import { Modal } from "../../components/common/modal.js";
import { Status } from "../../components/common/status-badge.js";
import { dateText } from "../../format.js";
import type { Memory, Repository as Repo } from "../../types.js";

export function ScopeChips({scope}:{scope:Memory["scope"]}) {
  const labels:Record<string,string>={paths:"路径",languages:"语言",modules:"模块",conditions:"条件"};
  const values=Object.entries(scope).flatMap(([kind,items])=>(items??[]).map(value=>({kind,value})));
  return <span className="scope-chips">{values.length?values.map(({kind,value},i)=><span className="chip" key={i} title={labels[kind]??kind}>{kind==="conditions"?"条件：":""}{value}</span>):<span className="chip">整个仓库</span>}</span>;
}

export function RulePanel({item,repository,candidates,busy,action,close,error}:{item:Memory;repository?:Repo;candidates:Memory[];busy:boolean;action:(item:Memory,name:string,value?:object)=>Promise<boolean>;close:()=>void;error:string}) {
  const [tab,setTab]=useState("rule"),[versions,setVersions]=useState<any[]|null>(null),[historyError,setHistoryError]=useState("");
  const [confirm,setConfirm]=useState<"deprecate"|"supersede"|null>(null),[replacement,setReplacement]=useState("");
  const next=candidates.find(candidate=>candidate.id===replacement),pr=`https://github.com/${repository?.fullName}/pull/${item.source.pullRequestNumber}`;
  useEffect(()=>{if(tab!=="history")return;const controller=new AbortController();setHistoryError("");setVersions(null);void api<{versions:any[]}>(`/api/memories/${item.id}`,{signal:controller.signal}).then(value=>setVersions(value.versions)).catch(cause=>{if(!controller.signal.aborted)setHistoryError(messageOf(cause));});return()=>controller.abort();},[tab,item.id,item.version,item.updatedAt]);
  return <><Modal drawer titleId="rule-detail-title" onClose={close}><div className="drawer-head"><span className="eyebrow">团队规则</span><button className="icon-button" aria-label="关闭规则详情" onClick={close}>×</button></div><div className="drawer-body">
    <h2 id="rule-detail-title">{item.title}</h2><div className="rule-status-line" role="status"><Status value={item.status} label={item.status==="CANDIDATE"&&item.activeVersion?"待确认更新":undefined}/><small>v{item.version} · 更新于 {dateText(item.updatedAt)}</small></div>
    {error&&<p className="alert" role="alert">{error}</p>}
    {item.status==="CANDIDATE"&&<p className="pending-note">{item.activeVersion?`当前 v${item.activeVersion} 继续用于审查；确认后才采用这次更新。`:"从 PR 讨论中识别的团队约定，确认后用于后续审查。"}{item.activeVersion&&<> <button className="text-button" onClick={()=>setTab("history")}>查看变更</button></>}</p>}
    {tab!=="rule"&&<button className="text-button back-link" onClick={()=>setTab("rule")}>← 返回规则</button>}
    {tab==="rule"&&<><section className="rule-section"><h3>规则</h3><p className="rule-content">{item.content}</p></section><section className="rule-section"><h3>适用范围</h3><ScopeChips scope={item.scope}/></section><section className="rule-section"><h3>规则来源</h3><p>{repository?.fullName}<br/><a href={pr} target="_blank" rel="noreferrer">PR #{item.source.pullRequestNumber} ↗</a> · {item.source.commentIds?.length??0} 条讨论</p><button className="text-button" onClick={()=>setTab("sources")}>查看依据 →</button></section><div className="rule-secondary"><span className="muted">{item.confidence>=.8?"高可信":item.confidence>=.5?"有待核实":"证据较弱"}</span><button className="text-button" onClick={()=>setTab("sources")}>为什么？</button><button className="text-button" onClick={()=>setTab("history")}>查看历史 →</button></div></>}
    {tab==="sources"&&<section className="rule-section"><h3>这条规则为什么存在</h3><p className="rule-content">{item.rationale}</p><a href={pr} target="_blank" rel="noreferrer">查看 PR #{item.source.pullRequestNumber} 的原始讨论 ↗</a><ul className="evidence-list">{item.evidence.map((entry,i)=><li key={i}><strong>{entry.kind==="human_comment"?"讨论依据":entry.kind==="code"?"代码依据":"相关依据"}</strong><p>{entry.detail}</p>{/^https:\/\//.test(entry.reference)?<a href={entry.reference} target="_blank" rel="noreferrer">查看来源 ↗</a>:<small>{entry.reference}</small>}</li>)}</ul><details><summary>可信度与不确定因素</summary><p>模型自评 {Math.round(item.confidence*100)}%，不代表校准后的正确率。</p>{item.uncertainties.length?<ul>{item.uncertainties.map((text,i)=><li key={i}>{text}</li>)}</ul>:<p>未记录额外不确定因素。</p>}</details></section>}
    {tab==="history"&&<section className="rule-section"><h3>版本与变更</h3>{historyError?<p className="alert" role="alert">{historyError}</p>:versions===null?<p role="status">正在加载历史…</p>:<ol className="version-list">{versions.map(version=><li key={version.version}><div><strong>v{version.version}{version.version===item.version?" · 当前展示":""}</strong><Status value={version.status}/></div><small>{dateText(version.updated_at)}</small><h4>{version.title}</h4><p className="rule-content">{version.content}</p><ScopeChips scope={version.scope}/><details><summary>修改依据</summary><p>{version.rationale}</p></details></li>)}</ol>}</section>}
    {tab==="technical"&&<section className="rule-section"><h3>技术信息</h3><dl><dt>Rule ID</dt><dd><code>{item.id}</code></dd><dt>Version</dt><dd>{item.version}</dd><dt>Source commit</dt><dd><code>{item.source.commitSha}</code></dd></dl><details><summary>原始范围与来源</summary><pre>{JSON.stringify({scope:item.scope,source:item.source},null,2)}</pre></details></section>}
  </div><footer className="drawer-footer">{item.status==="CANDIDATE"?<><button className="secondary" disabled={busy} onClick={()=>void action(item,"reject")}>忽略</button><a className="button secondary" href={`#rules/${item.id}/edit`}>编辑</a><button disabled={busy} onClick={()=>void action(item,"approve")}>{busy?"处理中…":item.activeVersion?"确认更新规则":"确认加入团队规则"}</button></>:<span className="muted">{item.status==="ACTIVE"?"用于后续 PR 审查":"保留来源与历史"}</span>}
    <details className="more-menu"><summary aria-label="更多规则操作">···</summary><div onClick={event=>{const menu=event.currentTarget.parentElement!;menu.removeAttribute("open");menu.querySelector("summary")?.focus();}}>{item.status==="ACTIVE"&&<a href={`#rules/${item.id}/edit`}>编辑规则</a>}<button onClick={()=>setTab("history")}>查看历史</button><button onClick={()=>setTab("technical")}>查看技术信息</button>{item.status==="ACTIVE"&&<>{candidates.length>0&&<button onClick={()=>setConfirm("supersede")}>用待确认规则替代</button>}<button className="danger" onClick={()=>setConfirm("deprecate")}>停用规则</button></>}</div></details>
  </footer></Modal>
  {confirm&&<Modal titleId="rule-confirm-title" onClose={()=>{if(!busy)setConfirm(null);}}><h2 id="rule-confirm-title">{confirm==="deprecate"?"停用这条团队规则？":"用另一条规则替代？"}</h2><p>{item.title}</p>{confirm==="deprecate"?<p className="muted">停用后将不再参与 PR Review，来源与历史仍然保留。</p>:<><label>选择待确认规则<select value={replacement} onChange={event=>setReplacement(event.target.value)}><option value="">请选择规则名称</option>{candidates.map(candidate=><option value={candidate.id} key={candidate.id}>{candidate.title}</option>)}</select></label>{next&&<div className="replacement-preview"><h3>{next.title}</h3><p>{next.content}</p><ScopeChips scope={next.scope}/></div>}<p className="muted">确认后，新规则生效，当前规则保留为历史。</p></>}{error&&<p className="alert" role="alert">{error}</p>}<div className="dialog-actions"><button className="secondary" autoFocus disabled={busy} onClick={()=>setConfirm(null)}>取消</button><button className={confirm==="deprecate"?"danger-button":""} disabled={busy||confirm==="supersede"&&!next} onClick={()=>void action(item,confirm,confirm==="supersede"?{candidateId:replacement}:{}).then(ok=>{if(ok)setConfirm(null);})}>{busy?"处理中…":confirm==="deprecate"?"确认停用":"替代并启用"}</button></div></Modal>}
  </>;
}
